name: publish

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build module
        shell: pwsh
        run: ./build.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: Ise.Cli
          path: out/Ise.Cli
